Add all_services input on tofu-plan

diff --git a/scripts/tofu-plan b/scripts/tofu-plan
--- a/scripts/tofu-plan
+++ b/scripts/tofu-plan
@@ -13,11 +13,21 @@ fi
 
 plan_error=false
 
-# Run plan in each service directory.
+if [ "$ALL_SERVICES" == "true" ]; then
+  dirs="$(ls -d terraform/services/*)"
+else
+  # When run on main, diff against the prior commit. When run on any
+  # other branch, diff against main.
+  ref="$([ "$(git branch --show-current)" == "main" ] && echo "HEAD^" || echo "main")"
+  echo "Using $ref for diff"
+
+  # Get all affected service directories.
+  dirs="$(git diff --name-only "$ref" -- 'terraform/services/**/*.tf' | xargs dirname | sort | uniq)"
+fi
+
 repo_root="$(git rev-parse --show-toplevel)"
-services_dir="$repo_root/terraform/services"
-for dir in $(ls "$services_dir"); do
-  cd "$services_dir"
+for dir in $dirs; do
+  cd "$repo_root"
   [ ! -d "$dir" ] && echo "No directory found at $dir. Skipping" && continue
   cd "$dir"
   [ ! -f "conf.sh" ] && echo "No conf.sh file in $dir. Skipping" && continue
@@ -28,38 +38,38 @@ for dir in $(ls "$services_dir"); do
     all)
       ;;
     account)
-      if [[ "$app" == "bcda" && ("$env" == "test" || "$env" == "prod") ]]; then
-        echo "Planning the $dir service against the $app-$env env for this account"
+      if [[ "$APP" == "bcda" && ("$ENV" == "test" || "$ENV" == "prod") ]]; then
+        echo "Planning the $dir service against the $APP-$ENV env for this account"
       else
-        echo "Skipping $dir service for the $app-$env environment"
+        echo "Skipping $dir service for the $APP-$ENV environment"
         continue
       fi
       ;;
     *)
       in_set=false
       for infra_env in $INFRA_ENVS; do
-        if [ "$infra_env" == "$app-$env" ]; then
+        if [ "$infra_env" == "$APP-$ENV" ]; then
           in_set=true
         fi
       done
       if [ "$in_set" != true ]; then
-        echo "Skipping $dir service for the $app-$env environment"
+        echo "Skipping $dir service for the $APP-$ENV environment"
         continue
       fi
       ;;
   esac
   echo "Running plan on $dir"
-  tofu init -reconfigure -backend-config="../../backends/${app}-${env}.s3.tfbackend"
-  export TF_VAR_app="$app"
-  export TF_VAR_env="$env"
+  tofu init -reconfigure -backend-config="../../backends/${APP}-${ENV}.s3.tfbackend"
+  export TF_VAR_app="$APP"
+  export TF_VAR_env="$ENV"
   tofu plan | tee "$temp_plan"
   if grep "Your infrastructure matches the configuration." "$temp_plan"; then
-    echo ":white_check_mark: No changes in $dir service on $app-$env env." >> $GITHUB_STEP_SUMMARY
+    echo ":white_check_mark: No changes in $dir service on $APP-$ENV env." >> $GITHUB_STEP_SUMMARY
   elif grep "OpenTofu encountered an error while generating this plan." "$temp_plan"; then
     plan_error=true
-    echo ":exclamation: Error in plan for $dir service on $app-$env env." >> $GITHUB_STEP_SUMMARY
+    echo ":exclamation: Error in plan for $dir service on $APP-$ENV env." >> $GITHUB_STEP_SUMMARY
   else
-    echo ":pencil: Changes in $dir service on $app-$env env. See plan." >> $GITHUB_STEP_SUMMARY
+    echo ":pencil: Changes in $dir service on $APP-$ENV env. See plan." >> $GITHUB_STEP_SUMMARY
   fi
 done
 
