Use -detailed-exitcode to check errors on tofu plan

diff --git a/scripts/tofu-plan b/scripts/tofu-plan
--- a/scripts/tofu-plan
+++ b/scripts/tofu-plan
@@ -1,8 +1,6 @@
 #!/bin/bash
 # Run tofu plan across all services. Used in the tofu-plan and tofu-apply workflows.
-set -e
 
-temp_plan=$(mktemp)
 temp_plan_out=$(mktemp)
 
 # Set temp file for summary if not running in github actions
@@ -15,8 +13,7 @@ fi
 tofu_error=false
 
 repo_root="$(git rev-parse --show-toplevel)"
-cd "$repo_root"
-for dir in $(ls terraform/services); do
+for dir in $(ls "$repo_root/terraform/services"); do
   cd "$repo_root/terraform/services/$dir"
   [ ! -f "conf.sh" ] && echo "Skipping $dir service due to no conf.sh file" && continue
   set -a
@@ -56,15 +53,14 @@ for dir in $(ls terraform/services); do
   fi
   export TF_VAR_app="$APP"
   export TF_VAR_env="$ENV"
-  tofu plan -out "$temp_plan_out" | tee "$temp_plan"
-  if grep "Your infrastructure matches the configuration." "$temp_plan"; then
+  if tofu plan -detailed-exitcode -out "$temp_plan_out"; then
     echo ":white_check_mark: No changes in $dir service on $APP-$ENV env." >> $GITHUB_STEP_SUMMARY
     continue
-  elif grep "OpenTofu encountered an error while generating this plan." "$temp_plan"; then
+  elif [ "$?" -eq "1" ]; then
     tofu_error=true
     echo ":exclamation: Error in plan for $dir service on $APP-$ENV env." >> $GITHUB_STEP_SUMMARY
     continue
-  else
+  else # Detailed exit code is 2, meaning changes are planned
     echo ":pencil: Changes in $dir service on $APP-$ENV env. See plan." >> $GITHUB_STEP_SUMMARY
   fi
   if [ "$APPLY" == "true" ]; then
